# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
      run: | 
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
        cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}
    - name: Build Image & Push
      env: 
        ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      run: | 
        docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/frontend:latest .
        docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/frontend:latest
  
  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone do Repositório
        uses: actions/checkout@v2

      - name: Autenticação no Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy Backend no  Cloud Run
        id: deploy
        run: |-
          gcloud run deploy backend \
            --quiet \
            --region  ${{ secrets.GOOGLE_REGION }} \
            --image ${{ secrets.ARTIFACT_REGISTRY_REPO }}/frontend:latest \
            --platform managed \
            --set-env-vars REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} \
            --allow-unauthenticated \
            --project ${{ secrets.GOOGLE_PROJECT_ID }} \
            --format json

