# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
    
    - name: Docker Login
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        ARTIFACT_REGISTRY:  ${{ secrets.ARTIFACT_REGISTRY}}
      run: | 
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
        cat key.json | docker login -u _json_key --password-stdin ${{ secrets.ARTIFACT_REGISTRY }}
    - name: Build Image & Push
      env: 
        ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      run: | 
        docker build -t ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest .
        docker push ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest

  DeployProd:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Auth GCP AppEngine
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to App Engine
        id: appengine
        env: 
          ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          image_url: ${{ secrets.ARTIFACT_REGISTRY_REPO }}/myapp:latest

      - name: Prod Test
        run: 'curl "${{ steps.appengine.outputs.url }}"'